import axios, { AxiosResponse } from 'axios';

/* This code was generated by ChatGPT 4 */

// Defines the structure of a message object
interface Message {
  role: string;
  content: string;
}

// Defines the parameters required for the API call
interface ApiCallParams {
  model: string;
  messages: Message[];
}

// Define the structure of the response from the GPT API
interface GPTResponse {
  id: string;
  object: string;
  choices: [
    {
      text: string;
      index: number;
      logprobs: null | object;
      finish_reason: string;
    }
  ];
}

// Function to make an API call to the OpenAI GPT endpoint
export const makeApiCall = async (apiKey: string, data: ApiCallParams): Promise<AxiosResponse<GPTResponse>> => {
  return axios.post('https://api.openai.com/v1/chat/completions', data, {
    headers: {
      'Authorization': `Bearer ${apiKey}`,
      'Content-Type': 'application/json'
    }
  });
};