import React from 'react';
import styles from './ButtonComponent.module.css';

/* Code generated by ChatGPT 4 */

// Define props for ButtonComponent
interface ButtonComponentProps {
  text: string; // The text to be displayed on the button
  onClick: () => void;  // Click event handler for the button
}
 
 // Define the ButtonComponent functional component
 const ButtonComponent: React.FC<ButtonComponentProps> = ({ text, onClick }) => {
  return (
    <button className={styles.fancyButton} onClick={onClick}>
      {text}
      <svg className={styles.buttonSvg} viewBox="0 0 200 100" preserveAspectRatio="none">
        <rect width="200" height="100" fill="transparent" className={styles.buttonRect} />
      </svg>
    </button>
  );
};

export default ButtonComponent;